title: Product
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: content
            field:
              type: markdown
              display: Content
              localizable: true
          -
            handle: price
            field:
              input_type: text
              antlers: false
              type: text
              display: Price
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: stock_levels
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Stock Levels'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: image
            field:
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Image
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: shopify_id
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Shopify ID'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
